### ISSUE TITLE
Replace gulp with hexo plugins

### ISSUE THREAD

**Issue by curbengh** [hexojs/site#1050]
:dog:fooding to demonstrate hexo's extensibility.

I believe hexo doesn't need gulp/grunt/brunch for deployment. The only benefits I notice with gulp is that it allows better control of execution order and put all tasks in a single file (could be a disadvantage in some situations though).

**Comment by curbengh** [comment]
I think other gulp plugins can be potentially replaced by hexo plugins.

**Comment by curbengh** [comment]
After gulp-responsive, I also want to tackle [gulp-rev](https://www.npmjs.com/package/gulp-rev), but I haven't figure out [gulp-rev-replace](https://www.npmjs.com/package/gulp-rev-replace).

``` js
const { extname } = require('path');
const { createHash } = require('crypto');

function revision() {
  const { route } = this;
  const routeList = route.list();
  const pngFiles = routeList.filter((path) => path.endsWith('.png') || path.endsWith('jpg'));

  return Promise.all(pngFiles.map((path) => {
    return new Promise((resolve, reject) => {
      const extension = extname(path);
      const assetPath = route.get(path);
      const assetData = [];
      assetPath.on('data', (chunk) => assetData.push(chunk));
      assetPath.on('end', async() => {
        if (assetData.length) {
          try {
            const input = Buffer.concat(assetData);
            const hash = createHash('sha1').update(input).digest('hex').slice(0, 10)

            route.set(path.replace(extension, hash.concat(extension)), input);
          } catch (err) {
            reject(err);
          }
        }
      });
    });
  }));
}

hexo.extend.filter.register('after_generate', revision);
```

**Comment by tomap** [comment]
I believe gulp-rev-replace is ancache buster for gulp. No need to replace it

**Comment by curbengh** [comment]
Just [realized](https://github.com/hexojs/site/pull/1138#issuecomment-539390282) we don't have to perform cache busting as Cloudfront can handle updated file.

**Comment by curbengh** [comment]
https://github.com/hexojs/site/pull/1138
