### ISSUE TITLE
Add hexo-filter-nofollow to plugins list and news

### ISSUE THREAD

**Issue by curbengh** [hexojs/site#1076]
https://github.com/hexojs/hexo-filter-nofollow/

**Comment by SukkaW** [comment]
So, what should we includes in the news? Just `hexo released a new official plugin` and `hexo-nofollow has been deprecated`?

**Comment by curbengh** [comment]
``` md
---
title: Official plugin hexo-filter-nofollow released
---

We released a new official plugin [hexo-filter-nofollow].
```

Then followed by the readme.

No need to mention hexo-nofollow since it was never an official plugin.

**Comment by SukkaW** [comment]
#1082

**Comment by curbengh** [comment]
https://github.com/hexojs/site/pull/1082 merged
