### ISSUE TITLE
github pages应该不支持https啊 为何hexo的主站就可以？

### ISSUE THREAD

**Issue by luodaoyi** [hexojs/site#110]
[https://hexo.io](https://hexo.io)
难道用的cloudflare的cdn?

**Comment by iissnan** [comment]
切换到 https 之后感觉速度变慢许多

**Comment by tommy351** [comment]
就是 Cloudflare

**Comment by Xuanwo** [comment]
cloudflare的https

@iissnan 因为需要先验证证书，要是到证书服务器连接慢的话。。

**Comment by luodaoyi** [comment]
Cloudflare 要改NS记录 坑啊
