### ISSUE TITLE
'undefined' on about page

### ISSUE THREAD

**Issue by pavelloz** [hexojs/site#1210]
https://hexo.io/about/

![image](https://user-images.githubusercontent.com/546845/68498119-6305f800-0256-11ea-975a-0c10c31315c6.png)

:)

**Comment by SukkaW** [comment]
Emmmm. That is quite strange.

![IMG_20191109_013805_931](https://user-images.githubusercontent.com/40715044/68498346-95811680-0291-11ea-9dfd-137750d0d73c.jpg)

**Comment by pavelloz** [comment]
Confirmed, it hides when on mobile :)

But on desktop:
![image](https://user-images.githubusercontent.com/546845/68498420-0eaf4800-0257-11ea-8447-82f97df768d7.png)
![image](https://user-images.githubusercontent.com/546845/68498437-1a027380-0257-11ea-8d1d-3e83408b03fb.png)

**Comment by tomap** [comment]
I tried to run it on windows locally, but it fails. That is another issue.
Will try on WSL

**Comment by pavelloz** [comment]
Just to be sure that its not my machine: https://webpagetest.org/result/191111_7E_cb47f2dc9ba6fa56bc6e5a6d69742320/

**Comment by tomap** [comment]
Can someone with a linux / macos at hand try? @hexojs/core

**Comment by SukkaW** [comment]
@tomap I might have a look at this.

**Comment by YoshinoriN** [comment]
@tomap @SukkaW 
This is a not platform dependent issue.
I creat PR #1216

**Comment by YoshinoriN** [comment]
@pavelloz 
We fixed. Thank you for your report :)
