### ISSUE TITLE
Remove lodash from doc ?

### ISSUE THREAD

**Issue by noraj** [hexojs/site#1290]
[The news](https://hexo.io/news/#Drop-Lodash-dependency-from-Hexo) are saying hexo dropped Lodash, so may I update the documentation to remove this ?

![image](https://user-images.githubusercontent.com/16578570/72479098-b61a9f00-37f3-11ea-8a6f-5053bdd894b2.png)

Or may be you think it is better to keep it and just tag it as outdated since hexo 4.2 ?

Tell me before I'm making a PR.

PS : I want to join hex org.

**Comment by SukkaW** [comment]
@noraj `lodash` itself still retains in `Locals.prototype._`, see this line: https://github.com/hexojs/hexo/blob/584b093b66f6f1d690dc98abee4c97c0b6029e46/lib/hexo/index.js#L372

We will only remove lodash in coming Hexo 5.0.

PS: If you really want to join Hexo core team, you should begin with understanding source code of Hexo and how it works. Currently there are [50 issues](https://github.com/hexojs/hexo/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request) under `hexojs/hexo` repo that are labeled as `feature-request`. Try to start implementing some of them and bring your PR to `hexojs/hexo`.

**Comment by noraj** [comment]
> PS: If you really want to join Hexo core team, you should begin with understanding source code of Hexo and how it works. Currently there are [50 issues](https://github.com/hexojs/hexo/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request) under `hexojs/hexo` repo that are labeled as `feature-request`. Try to start implementing some of them and bring your PR to `hexojs/hexo`.

I don't plan to help with the core of hexo but rather helping adding/fixing helpers(), documentation or some official plugin stuff. I'm currently working at creating a huge theme for hexo so I'm starting to see some internals of Hexo.
