### ISSUE TITLE
An Email from KeyCDN

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/site#132]
> Hi guys
>
> I've seen that you're all contributing to hexo.io which is a awesome framework that I've been using as well!
> At KeyCDN we're interested in a closer integration with hexo.io and KeyCDN. What do you think? 
>
> KeyCDN is operating a high-performance content delivery network (CDN) made in Switzerland that supports the next generation web protocol HTTP/2. We are dedicated to make content delivery smarter and less expensive with a true pay-as-you-go pricing model (no charges for HTTP requests and free custom SSL).Looking forward to your feedback. 
> 
> Kind regards,
> Jonas
> https://www.keycdn.com

What do you think?

**Comment by leesei** [comment]
What area would they like to contribute?

@tommy351

**Comment by tommy351** [comment]
I don't know. This service seems like Cloudflare?

**Comment by Xuanwo** [comment]
What's the difference between then?
If not much, we don't need to change cloudflare into them.
