### ISSUE TITLE
Sorry for resulting in the site down for about 2 hours

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/site#134]
Hello, everyone, I'm @Xuanwo, and I made a mistake today morning which made the dite down for about 2 hours.
Thank @zhangwenan 's report, ref https://github.com/hexojs/hexo/issues/1642 , I convert my commit and rebuild the site, but because the site use cloudflare as CDN, so until now, the site may still have some problem.

That's all. And this mistake makes me think more.

We should modify the build script that when we meet an error, we should stop the build instead of uploading the wrong page. I will pull a request late about this.

ref: https://travis-ci.org/hexojs/site/builds/95942765

I hope my mistake will not lead to a disaster, :disappointed: .

**Comment by Xuanwo** [comment]
@tommy351 If error happened in https://github.com/hexojs/site/blob/master/.travis/deploy.sh#L18 , travis ci will not return non zero exit code which will result in wrong deploy.

**Comment by leesei** [comment]
No problem. I don't think any cat died in this incident.

That's weird, it seems hexo did not exit with error code upon this failure.

**Comment by tommy351** [comment]
It's a bug of hexo-cli and it's fixed in 0.2.0. hexo-cli 0.2 will be shipped in hexo 3.2.

**Comment by Xuanwo** [comment]
Nice work.
