### ISSUE TITLE
Update installation docs: currently installation docs create errors and do NOT work

### ISSUE THREAD

**Issue by cekvenich** [hexojs/site#1370]
I recently recommended Hexo to a client. Sadly the installation docs don't work.
yarn (old version) is required and not mentioned in the docs:
https://hexo.io/docs

See https://github.com/hexojs/hexo-cli/issues/176

The docs need to be updated to mention the need for yarn (old version) else hexo init fails.

I think it is important for hexo community to grow, and one factor is how easy it is to adopt hexo. The first hexo command you run is 'init' and it fails. So please update docs to mention an old version of yarn.

(aside: yarn used to be cool years back, but npm works. On my other project, I use a download script to get a zip example file hosted in /doc folder publically. I'm happy to write up an example. This way yarn or git install is not needed - for designers and clients to make it easy to use hexo)

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo-cli/pull/227

**Comment by stevenjoezhang** [comment]
yarn 3 is now supported: https://github.com/orgs/hexojs/discussions/5035#discussioncomment-4564807
