### ISSUE TITLE
Very difficult to understand how to customization of themes using Hexo

### ISSUE THREAD

**Issue by rwagh** [hexojs/site#14]

**Comment by Xuanwo** [comment]
well, you just need to learn how to use ejs or swig

**Comment by leesei** [comment]
I think Hexo lacks documentation on the flow and data available to the theme.
For example I'm still not sure who is responsible for generating the index page for `tags` and `categories`, theme or generator?

**Comment by tommy351** [comment]
@leesei 
1. Generators generates routes; themes decides the appearance of your site.
2. You can specify the layout in front-matter. Hexo will try to find the corresponding template files in your theme or use the layout specified in the generator as the fallback.

**Comment by Xuanwo** [comment]
![image](https://cloud.githubusercontent.com/assets/5351546/8490540/6f1481c2-215d-11e5-817f-2cefb880b7ef.png)
How to deal with this kind of issues?
Just close it?

**Comment by leesei** [comment]
Now that I've read a book on WordPress I can get hold of how Hexo works and the philosophy behind it.
The gist is that hexo process the source files and prepare data structures and it is up to the theme to do the rendering.

There are conventions in the [doc](https://hexo.io/docs/templates.html) for choosing which layout to load in the theme.
I agree that there are rooms for improvements in the docs.
New helper functions will be coming and customizers are recommended to study existing themes to see how they works.
