### ISSUE TITLE
Title broken in docs

### ISSUE THREAD

**Issue by jackycute** [hexojs/site#142]
<img width="944" alt="2016-01-02 11 26 03" src="https://cloud.githubusercontent.com/assets/2639151/12075370/acd343f6-b143-11e5-8c34-5a8e81d95040.png">
https://hexo.io/docs/server.html
As you see, the title became: `hexo-server">hexo-server` which should only be `hexo-server`.
Also the TOC occurred the same issue.

**Comment by Xuanwo** [comment]
Well, I thought I fixed it, but it seems not.
I will fix it after a while, thanks~

**Comment by tommy351** [comment]
Fixed by updating hexo-renderer-marked
