### ISSUE TITLE
Need to update starter project

### ISSUE THREAD

**Issue by RammusXu** [hexojs/site#1521]
Since the theme is using 3 years ago code base. It's pretty buggy. Thanks.
```
$ hexo init blog
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
```

https://github.com/hexojs/hexo-starter

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-cli/issues/236
I'm closing this issue. Please join the discussion there :)

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo-starter/pull/45
