### ISSUE TITLE
theme列表中的Raytaylorism预览链接是个H网

### ISSUE THREAD

**Issue by Thetiso** [hexojs/site#1561]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

如题,赶紧改一下吧

**Comment by Thetiso** [comment]
> ![image](https://user-images.githubusercontent.com/15902347/97648797-a291a980-1a90-11eb-912c-e5fbc42ceeb1.png)
> 
> 这个么？我访问正常啊
> 
> ![image](https://user-images.githubusercontent.com/15902347/97648833-bb9a5a80-1a90-11eb-8e58-eb1ee94f6129.png)

![Uploading image.png…]()
手机4G打开显示的是这个，  电脑打开会跳转91.....

**Comment by Thetiso** [comment]
> ![image](https://user-images.githubusercontent.com/15902347/97648797-a291a980-1a90-11eb-912c-e5fbc42ceeb1.png)
> 
> 这个么？我访问正常啊
> 
> ![image](https://user-images.githubusercontent.com/15902347/97648833-bb9a5a80-1a90-11eb-8e58-eb1ee94f6129.png)

![image](https://user-images.githubusercontent.com/8968567/97820592-c3087080-1ce9-11eb-8719-d46b140838f0.png)

**Comment by jiangtj** [comment]
Emmm, 手机上一样正常，建议您检查下您的手机或者路由，网络是否被黑客劫持

**Comment by Thetiso** [comment]
> Emmm, 手机上一样正常，建议您检查下您的手机或者路由，网络是否被黑客劫持

哈哈哈  一脸懵逼  刚才用chrome无痕模式跑手机模式 打开的是对的
