### ISSUE TITLE
Docs page have a error about "hexo-renderer-pug"

### ISSUE THREAD

**Issue by knoxnoe** [hexojs/site#1565]
## Please check the site :"https://hexo.io/news/2019/10/19/hexo-renderer-jade-0-5_hexo-renderer-pug-1/"

```
-  "hexo-renderer-jade": "^0.4.1",
+  "hexo-rederer-pug": "^1.0.0",
```
rederer -----> renderer

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/site/commit/7ce720752b3f003e37c626d924ae58942068f96a
