### ISSUE TITLE
internal links in zh-cn docs not correct

### ISSUE THREAD

**Issue by lgh06** [hexojs/site#163]
internal links in zh-cn docs not correct,lack of zh-cn/docs/ prefix in zh-cn/docs/setup.md and more files.

And, the auto-genetated href is something like http://localhost:4000/zh-cn/docs/writing.html#u6A21_u7248_uFF08Scaffold_uFF09 ,seems not support Chinese?

**Comment by tommy351** [comment]
The reason is because hexo-renderer-marked didn't handle Chinese header properly. I have released 0.2.10 and it should be fixed in the next generation.
