### ISSUE TITLE
I would like to join Hexo

### ISSUE THREAD

**Issue by TriDiamond** [hexojs/site#1632]
Hi, I am TriDiamond, an active open source web developer. I have made two themes for Hexo, [Obsidian](https://github.com/TriDiamond/hexo-theme-obsidian) and [Aurora](https://github.com/auroral-ui/hexo-theme-aurora). 

I have submitted the new theme's [PR](https://github.com/hexojs/site/pull/1630) and I have notice Hexo's PR review is not as active as before. Since I am active on Open Source right now. I would like to join Hexo as a member and help out on the Hexo theme side of the development. Probably will work on some of the features in Hexo core. 

I am not sure where to look for an Admin on the website, but I see a message in the about section, stating posting an issue if one have question about joining Hexo. 

Hope this get to one of the Admin in Hexo team, thanks.

**Comment by stevenjoezhang** [comment]
CC @hexojs/core
