### ISSUE TITLE
BUG: Hexo should NOT process JS files as Markdown

### ISSUE THREAD

**Issue by lorezyra** [hexojs/site#1696]
Currently using HEXO version 5.4.0.

Added images and JS files to a folder to reference in a markdown file. However, HEXO processed the files and created HTML for these files as though they were MD files.

Request: please have HEXO ignore *.js files and just add to the folder for the HTML to reference (treat JS like an image file).

**Comment by stevenjoezhang** [comment]
I'm closing this issue. Please join the discussion here https://github.com/hexojs/hexo/issues/4774 :)

**Comment by lorezyra** [comment]
This report is on the wrong project. Moving to: https://github.com/hexojs/hexo/issues/4774
