### ISSUE TITLE
hexo g生成访问public文件夹下的index.html是原文件信息

### ISSUE THREAD

**Issue by xieyang0715** [hexojs/site#1740]
![image](https://user-images.githubusercontent.com/43713217/143732135-09261213-e972-42cc-9e1a-52834f3e4ac4.png)
官网说可以直接使用hexo g生成的public文件夹下的内容，但是我直接打开public文件夹下的index.html任然没有解析，就像下面这样
{% extends '_layout.swig' %} {% import '_macro/post.swig' as post_template %} {% import '_macro/sidebar.swig' as sidebar_template %} {% block title %}{{ config.title }}{% if theme.index_with_subtitle and config.subtitle %} - {{config.subtitle }}{% endif %}{% endblock %} {% block page_class %} {% if is_home() %}page-home{% endif -%} {% endblock %} {% block content %}
{% for post in page.posts %} {{ post_template.render(post, true) }} {% endfor %}
{% include '_partials/pagination.swig' %} {% endblock %} {% block sidebar %} {{ sidebar_template.render(false) }} {% endblock %}
![image](https://user-images.githubusercontent.com/43713217/143732180-21e5f138-506f-41f6-aad5-3e463ca3a04f.png)
该html文件就跟没解析一样，这个改怎么解决

**Comment by stevenjoezhang** [comment]
你用的是什么主题？

**Comment by xieyang0715** [comment]
> 你用的是什么主题？

next

**Comment by stevenjoezhang** [comment]
你用的是旧版，重新安装新版就能解决： https://github.com/next-theme/hexo-theme-next

**Comment by xieyang0715** [comment]
> 你用的是旧版，重新安装新版就能解决： https://github.com/next-theme/hexo-theme-next

确实是版本问题
