### ISSUE TITLE
'simple-black' theme preview redirects to malicious website

### ISSUE THREAD

**Issue by glennsl** [hexojs/site#1844]
When clicking the preview link for the `simple-black` theme, uBlock Origin thankfully blocked an attempt to hijack the link through redirection to a malicious website, instead showing me this:

![2022-03-27-224121_530x309_scrot](https://user-images.githubusercontent.com/5207036/160300185-d36ecbec-e6b9-48c8-8729-c27ce3867a37.png)

I suggest either replacing or, if possible, removing the preview link. Or if neither is feasible, remove the theme entirely.

**Comment by stevenjoezhang** [comment]
I have changed the preview link to GitHub repo URL: https://github.com/hexojs/site/commit/5b436656bc2485afa4c79c4ae070f704896878d0
I'll try to contact the theme owner later
