### ISSUE TITLE
What is the license, please?

### ISSUE THREAD

**Issue by zeritonius** [hexojs/site#1980]
In this file:
https://github.com/hexojs/site/blob/master/LICENSE
it says the license is "MIT".

On the top of this page:
https://github.com/hexojs/site
it says the license is "MIT", yet at the bottom of it it says "CC BY 4.0".

Which one is it?
a) MIT
b) CC BY 4.0
c) MIT or CC BY 4.0, at the choosing of the user.

Thank you.

**Comment by SukkaW** [comment]
The content of the hexo documentation is released under the CC BY 4.0 license.

Anything that is not the content (the theme used by the hexo docs, the CSS, the JS, the GitHub Action script used to validate the PR, etc.) is released under the MIT license.

**Comment by zeritonius** [comment]
Thank you so much for your explanation. Now it's crystal clear to me.
