### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by embedBook** [hexojs/site#2001]
I have clone the master code and install npm,hexo-cli ,but occurs failed when npm intall ,as follows:
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by stevenjoezhang** [comment]
These are just some warnings, you can run the following command to see if the deps are installed:
```
npx hexo s
```

**Comment by embedBook** [comment]
> These are just some warnings, you can run the following command to see if the deps are installed:
> 
> ```
> npx hexo s
> ```

npm ERR! could not determine executable to run

what's the node version? my node version 18.15

**Comment by yoshinorin** [comment]
I assume, this issue is not related this repos.
Please submit a question to [discuttion](https://github.com/orgs/hexojs/discussions) if you have still facing the problem.
