### ISSUE TITLE
Does the theme page no longer have maintenance?

### ISSUE THREAD

**Issue by mulder21c** [hexojs/site#2048]
Does the theme page no longer have maintenance?
I've created a PR by creating a new theme, but it's been neglected for more than two months without approval or rejection.
I hope someone to give me an answer.

**Comment by yoshinorin** [comment]
@mulder21c 
Sorry, perhaps  we didn't notice it. We might not be merged if PR has below issues.

1. Just copy or violate the copyright or other theme
2. Example domain or repository is 404 or invalid
3. or etc...

In this case of your theme, I don't see any issues. So if you could submit the PR again, we will merge it.
Additionally in PR #2038, we are splitted the theme files. We apologize for the inconvinience, but please submit the PR again.

Thank you :)

**Comment by mulder21c** [comment]
OK, I understand.

I will fix theme file and submit PR again

Thx.
