### ISSUE TITLE
Use crowdin to translate documents

### ISSUE THREAD

**Issue by uiolee** [hexojs/site#2119]
As for my experiences in other repos, it may be better to put [Crowdin](https://crowdin.com/) into practice. Strings may be updated there for approval.

_Originally posted by @jasonren0403 in https://github.com/hexojs/site/issues/133#issuecomment-954872464_
            

--------------

I'm looking forward to using crowdin to translate our documents.

I contributed some translations to pnpm on crowdin and did some testing using hexo'site.
Crowdin can sync the changes of the original language into other languages, which I think is a very very good feature.

**Comment by uiolee** [comment]
I had made some test, and it perform not bad.

- configuration and CI: https://github.com/hexojs/site/compare/master...uiolee:site:crowdin
- repo(github): https://github.com/uiolee/site/
- project(crowdin): https://crowdin.com/project/hexo-site

**Comment by yoshinorin** [comment]
@uiolee  cc: @hexojs/core 
LGTM 🎉 
Can we proceed this?

**Comment by tomap** [comment]
Just to start small, I would do it for a small minor subset (like a single small page) to work the angles before applying to all?

**Comment by uiolee** [comment]
> Just to start small, I would do it for a small minor subset (like a single small page) to work the angles before applying to all?


![files](https://github.com/hexojs/site/assets/22849383/9820fd8c-8e8d-4637-8e5e-a432298bfc1a)

We now have about 45 files.

You can add by folder if you wish. Otherwise you need to write more rules

![crowdin](https://github.com/hexojs/site/assets/22849383/d8b24e29-b1e8-421b-84ee-8be18e5c28f9)

**Comment by yoshinorin** [comment]
> manager register an account and create a project in Crowdin.

Is it possible to create org project to crowdin?

> generate a github token and add it into secrets of hexo/site.
> member account or new a bot account.

I think bot account is better, but how should we manage it? (e.g: share password)
If its difficult member account's token is acceptable.

> Just to start small, I would do it for a small minor subset (like a single small page) to work the angles before applying to all?

Personally, I think it's okay to do it all at once.

1. To small start is complex and time-consuming
2. Within the previous discussions in the Hexo project, there have been several instances where no conclusion was reached, leading to a lack of progress.
3. https://crowdin.com/project/hexo-site seems works well
4. Even if there were any issues, it wouldn't be a significant problem compared to bugs into the program.

**Comment by uiolee** [comment]
> Is it possible to create org project to crowdin?

I don't see such a description in crowdin. But crowdin project can add multiple administrators.

> I think bot account is better, but how should we manage it? (e.g: share password)
> If its difficult member account's token is acceptable.

the github toekn is used to summit PR. I think we dont need do anything else.

**Comment by yoshinorin** [comment]
@uiolee 
Can we use your project?

https://crowdin.com/project/hexo-site

**Comment by uiolee** [comment]
We'd better create a new one. I may have mixed in something weird while testing

**Comment by yoshinorin** [comment]
> We'd better create a new one. I may have mixed in something weird while testing

Would you please create a new one?

**Comment by uiolee** [comment]
ok. I have created a new. https://crowdin.com/project/hexo
[![Crowdin](https://badges.crowdin.net/hexo/localized.svg)](https://crowdin.com/project/hexo)

**Comment by D-Sketon** [comment]
https://crowdin.com/profile/d-sketon
