### ISSUE TITLE
Proposal: Japanese Translation of the Documentation

### ISSUE THREAD

**Issue by KentarouTakeda** [hexojs/site#2151]
Refer to #2150 

In an effort to expand Hexo's presence in Japan, I propose adding Japanese documentation to the Hexo official website.

Translating the current documentation is expected to be easy. However, consideration must be given to the ongoing maintenance required with the addition of a new language.

Should the original English documentation receive updates, I am willing to contribute to the Japanese version's updates as much as possible. However, my availability may vary.

With this in mind, I would appreciate feedback on my initiative from the maintainers. If acceptable, I am eager to continue with the translation work, as detailed in the draft pull request linked to this issue.

**Comment by yoshinorin** [comment]
> However, consideration must be given to the ongoing maintenance required with the addition of a new language. Should the original English documentation receive updates, I am willing to contribute to the Japanese version's updates as much as possible.

As far as I know, changes to the documentation over the past few years have mostly been limited to feature additions when new versions are released. In addition we are currently considering migrating to Crowdin, so I think it will make it easier to check the differences between English and other languages.

> However, my availability may vary.

All contributors and maintainers also. It is not necessary to worry.

One thing I'm wondering about is whether we'll need to merge PR #2150 before migrate to Crowdin (In other words, whether we can migrate only Japanese docs to Crowdin later additionaly). But I think we can figure it out somehow.

Anyway I'll review #2150 in this weekend or next weekend.

Thank you :)
