### ISSUE TITLE
npm install goes wrong

### ISSUE THREAD

**Issue by laodengjuntuan** [hexojs/site#2227]
### Check List

- [x] I have already read README.
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the latest version of this repository.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo.
- [X] My Node.js is matched the required version.

### Describe the bug

I encountered issues with `npm install`. It seems to be caused by some packages being too old or not updated for a long time, making them incompatible with higher version of Node or npm.
I tried several solutions, such as switching the Node version to 14.0.0, which resolved some issues but introduced new ones. Using `cnpm` also led to new problems.

Finally, I successfully installed everything using Node version 20.13.1 and `cnpm@7.1.1`
It took me six hours to resolve these issues, and I hope someone can update the old packages, dependencies, or documentation to save others from spending six hours on this.

### Expected behavior

I hope someone can update related packages to fit higher version of Node and npm, or upload the `package-lock.json` file, or specify the required version of Node and npm. 
This would help solve the `npm install` failure.

### How to reproduce

1. Initially, I tried installing with Node version 20.13.1 and encountered errors.
2. Then, I switched to Node version 14.0.0, which is the minimum requirement for Hexo, and encountered errors.
3. Next, I tried using Node version 14.18.0 with `cnpm` and still encountered errors.
4. Then, I went back to Node version 20.13.1 witch `cnpm` and encountererd errors again.
5. Finally, I used Node version 20.13.1 and downgraded `cnpm` to version 7.1.1, which resolved the issues.

### Screenshots

When Node version is 20.13.1![image](https://github.com/user-attachments/assets/941e53d2-7dcf-4fd5-b6cf-21efc991fee6)
When Node version is 14.0.0![image](https://github.com/user-attachments/assets/111b4b03-2837-425e-809c-3892f807c588)
When Node version is14.0.0 with cnpm version 7.1.1![image](https://github.com/user-attachments/assets/18ef45ef-e98d-4ab8-8ca7-ec65873fc45e)
When Node version is 20.13.0 with cnmp version 7.1.1，reported lots of deprecate，but went well。![image](https://github.com/user-attachments/assets/875d7d11-27fe-46eb-a07a-32410fd8fe8a)

### Environment information

```text
windows10，node@v20.13.1，npm@10.5.2，cnpm@7.1.1
```

**Comment by D-Sketon** [comment]
> getaddrinfo ENOENT raw.githubusercontent.com

Your npm can't resolve the raw.githubusercontent.com domain name. It's usually a network problem.

**Comment by laodengjuntuan** [comment]
> > getaddrinfo ENOENT raw.githubusercontent.com
> 
> Your npm can't resolve the raw.githubusercontent.com domain name. It's usually a network problem.

I added `185.199.108.133 raw.githubusercontent.com` to my hosts file. It seems to work but another problem appear.
![image](https://github.com/user-attachments/assets/c7b66c10-a6d2-46a4-bbbd-8b843c935082)

**Comment by yoshinorin** [comment]
This issue is not related to the repository, so I am closing it. If the problem persists, please submit a new question to [discussion](https://github.com/orgs/hexojs/discussions).

**Comment by uiolee** [comment]
The continuous build has been working fine. dependabot will update dependencies. I don't think there is anything wrong with `site`. 
You should check your local environment and network
