### ISSUE TITLE
How to remove the search box without causing scroll bug ?

### ISSUE THREAD

**Issue by dujcel** [hexojs/site#248]
I've tried many ways to remove the search bar since I don't want it in my site, including:
1. remove the algolia segment in _config.yml
2. remove the corresponding script in after_footer.swig
3. change the css of the search box to hide it.

However, **once the search box is not displayed or the script in after_footer is removed**, the strange thing happen:
**click on one news link in the news page, then swipe back to the previous page, I can't scroll up and down !**

I use safari on mac. Any helps are welcomed. Thank you!

**Comment by Xuanwo** [comment]
Looks like a theme problem

**Comment by zeroby0** [comment]
Which search box are you talking about? The one in navigation bar or the one in Themes/?
I was able to remove the one in navigation bar by removing search key in theme/navy/languages/en.yml and then commenting out div for search in themes/navy/layout/partial/header.swig

this part

``` html
   <div id="search-input-wrap">
       <div id="search-input-icon">
           <i class="fa fa-search"></i>
       </div>
           <input type="search" id="search-input" placeholder="Search...">
   </div>
```

After that, search box disappeared, and there was no bug in scrolling so far.
I will host the code in my [repository](https://github.com/zeroby0/website), its not complete, yet.

**Comment by curbengh** [comment]
Please direct the inquiry to the theme dev.
