### ISSUE TITLE
Add document describing plugin loading behavior

### ISSUE THREAD

**Issue by leesei** [hexojs/site#262]
With [this implementation](https://github.com/hexojs/hexo/blob/master/lib/hexo/load_plugins.js)

> You either DO NOT define plugins and let Hexo search for them or define ALL the plugins you used.

But this is not documented and causing misuse of `config.plugins`, https://github.com/hexojs/hexo/issues/1848#issuecomment-230172282.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/1670

**Comment by stevenjoezhang** [comment]
Reverted in https://github.com/hexojs/hexo/pull/4475
