### ISSUE TITLE
CSS not loaded when used in a sub directory of a domain.

### ISSUE THREAD

**Issue by zeroby0** [hexojs/site#265]
Hi! When a hexo site is installed in subdirectory of a domain, it fails to retrieve CSS and also _I believe_ JS and other files.  
For example, when contents of public folder are uploaded to domain.com/demo/, then CSS files are being retrieved from domain.com/css, instead of domain.com/demo/css.  
This is a problem, because it limits its usage in Github pages for a project.  
I used the same site in this repository and launched it in gh-pages branch of one of my repositories, no CSS was available, and inspector showed that browser tried to retrieve css from username.github.io, not username.github.io/repository.

**Comment by Xuanwo** [comment]
Which theme you use? And please paste your `_config.yml`

**Comment by zeroby0** [comment]
Navy theme used for hero site. 
Here is my _config.yml

title: Aravind
subtitle: "Hi"
description: "Some desc.."
author: Aravind Reddy V
language: en
timezone: UTC
url: https://hnode.github.io/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md 
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

relative_link: false
disqus_shortname: hexojs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo

twitter: hexojs
github: hexojs/hexo

**Comment by zeroby0** [comment]
I tried changing root to /demo/ from /, though there was an overall improvement like css files are being retrieved, logo and some other parts are missing.

**Comment by Xuanwo** [comment]
you should both change 
```
url: https://hnode.github.io/
root: /
```
to
```
url: https://hnode.github.io/demo
root: /demo/
```

**Comment by zeroby0** [comment]
Thanks, I'll try :)
