### ISSUE TITLE
How to add scripts to head of files generated.

### ISSUE THREAD

**Issue by zeroby0** [hexojs/site#267]
Is there an easier way to add elements to head of files? like a custom style sheet or javascript file for a contact form, etc.  
This might be possible via templates and stuff, but it'd be an overkill and not customisable, is there a way in which a _line_ could be added to head in Markdown file and the line will then be added to head of html? Or some other approach?

**Comment by Xuanwo** [comment]
Just edit the theme's layout.
In MD files, you can insert html code.
