### ISSUE TITLE
netlify build error

### ISSUE THREAD

**Issue by solsenfinovertech** [hexojs/site#387]
I just keep getting:
`Invalid netlify.toml file: Invalid publish directory: /public`

The site does build locally via `npm install && npm run build`

Can you see what might be wrong?
https://github.com/solsenfinovertech/tractr-dev-guide/blob/master/netlify.toml

**Comment by outloudvi** [comment]
Works for me with `hexo generate` & `/public`. Actually, an [official guide](https://www.netlify.com/blog/2015/10/26/a-step-by-step-guide-hexo-on-netlify/ ) is presented.
