### ISSUE TITLE
Missing list of available values on Hexo helpers' options.

### ISSUE THREAD

**Issue by htkoca** [hexojs/site#427]
The default values are shown but not all available values are shown. (How will we know what else is accepted?)

Example for: 
```
<%- list_tags([options]) %>
```
| Option | Description | Default |
|---|---|---|
| `orderby` | Order of categories | `name` |
| `style` | Style to display the tag list. list displays tags in an unordered list. | `list` |

What other values are available other than `name` or `list`?

**Comment by NoahDragon** [comment]
Could you please elaborate?

**Comment by htkoca** [comment]
It was a bit late when I posted this, and it's a bit silly now that I read it. Updated the issue contents in original post !

**Comment by curbengh** [comment]
`List` [helpers](https://hexo.io/docs/helpers#List) now show complete options.
I also added example of [transform](https://github.com/hexojs/site/pull/979) option.
