### ISSUE TITLE
Inconsistent template engine examples throughout documentation

### ISSUE THREAD

**Issue by htkoca** [hexojs/site#428]
Front matter, asset folders uses one template engine, while helpers uses another.

**Comment by NoahDragon** [comment]
We definitely have to rewrite it as Hexo 3.0 is totally different from 2.0

**Comment by Steef435** [comment]
Would be nice if at least a notice of it being out of date would be added. I spent some hours figuring out why the HAML parser didn't work, rewriting it with a different backend in the process, only to finally find out that the "body" variable simply doesn't exist anymore. (and was replaced by page.content? It seems to work for posts but not for static pages)

**Comment by stevenjoezhang** [comment]
The documentation has been updated with the release of Hexo 3.0 and 4.0.
I'm closing this issue, please re-open if it is still outstanding.
