### ISSUE TITLE
Horisontal scroll on all pages

### ISSUE THREAD

**Issue by ruskakimov** [hexojs/site#448]
## Screenshot
![screen shot 2017-03-20 at 9 42 30 pm](https://cloud.githubusercontent.com/assets/5536948/24102266/5ab5e4ea-0db6-11e7-831b-10e7f9b19aa2.png)

It seems like `.mobile-nav-dimmer` is causing the problem, since if you display none it, the scroll goes away.

**Comment by NoahDragon** [comment]
Thanks for the PR.

**Comment by 0x5e** [comment]
![image](https://cloud.githubusercontent.com/assets/5144674/25783055/273a7eda-3388-11e7-84c2-399eade9d577.png)

Still have problem in iOS 10.3.1. `overflow-x: hidden` not work on safari: http://stackoverflow.com/questions/14270084/overflow-xhidden-doesnt-prevent-content-from-overflowing-in-mobile-browsers
