### ISSUE TITLE
頁面錯誤

### ISSUE THREAD

**Issue by GuanAllen** [hexojs/site#482]
- [x] [配置](https://hexo.io/zh-tw/docs/configuration.html)–[網址](https://hexo.io/zh-tw/docs/configuration.html#網址)—連結錯誤
>permalink 文章 [永久連結](https://hexo.io/zh-tw/docs/docs/permalinks.html) 的格式 :year/:month/:day/:title/

- [x] [配置](https://hexo.io/zh-tw/docs/configuration.html)–[網址](https://hexo.io/zh-tw/docs/configuration.html#網址)—顯示錯誤
>{% note info 網站存放在子目錄 %} 如果您的網站存放在子目錄中，例如 `http://yoursite.com/blog`，則請將您的 `url` 設為 `http://yoursite.com/blog` 並把 `root` 設為 `/blog/`。 {% endnote %}

- [x] [配置](https://hexo.io/zh-tw/docs/configuration.html)–[寫作](https://hexo.io/zh-tw/docs/configuration.html#寫作)—連結錯誤
> post_asset_folder 啟動 [Asset 資料夾](https://hexo.io/zh-tw/docs/docs/permalinks.html)  false

- [x] [主題](https://hexo.io/zh-tw/docs/themes.html)–[發佈](https://hexo.io/zh-tw/docs/themes.html#發佈)—顯示、資訊錯誤
>把檔案庫（repository）複製到電腦上，並安裝相依套件。
{% code %} `$ git clone https://github.com//site.git` `$ cd site` `$ npm install` {% endcode %}

應該是`$ git clone https://github.com/hexojs/site`

- [x] [主題](https://hexo.io/zh-tw/docs/themes.html)–[languages](https://hexo.io/zh-tw/docs/themes.html#languages)–連結錯誤
>**languages**
>語言資料夾。請參見 [本地化 (i18n)](https://hexo.io/zh-tw/docs/localization.html)。

（連結標題為「[國際化(i18n)](https://hexo.io/zh-tw/docs/internationalization.html)」）

**Comment by GuanAllen** [comment]
https://hexo.io/zh-tw/docs/themes.html

>把檔案庫（repository）複製到電腦上，並安裝相依套件。
{% code %} `$ git clone https://github.com//site.git` `$ cd site` `$ npm install` {% endcode %}

應該是`$ git clone https://github.com/hexojs/site`

[![screen shot 2017-05-17 at 12 08 18 am](https://cloud.githubusercontent.com/assets/14134195/26116245/ff1f3724-3a94-11e7-84b6-8b3b47db1632.png)](https://hexo.io/zh-tw/docs/themes.html)

**Comment by GuanAllen** [comment]
### 連結錯誤
https://hexo.io/zh-tw/docs/themes.html

⭕️ https://hexo.io/zh-tw/docs/internationalization.html
❌  https://hexo.io/zh-tw/docs/localization.html

>**languages**
>語言資料夾。請參見 [本地化 (i18n)](https://hexo.io/zh-tw/docs/localization.html)。

**Comment by GuanAllen** [comment]
## [配置](https://hexo.io/zh-tw/docs/configuration.html)

### [網址](https://hexo.io/zh-tw/docs/configuration.html#網址)—連結、顯示錯誤

- [ ] 連結錯誤
⭕️ https://hexo.io/zh-tw/docs/permalinks.html
❌ https://hexo.io/zh-tw/docs/docs/permalinks.html
>permalink 文章 [永久連結](https://hexo.io/zh-tw/docs/docs/permalinks.html) 的格式 :year/:month/:day/:title/
- [ ] 顯示錯誤
>{% note info 網站存放在子目錄 %} 如果您的網站存放在子目錄中，例如 `http://yoursite.com/blog`，則請將您的 `url` 設為 `http://yoursite.com/blog` 並把 `root` 設為 `/blog/`。 {% endnote %}

### [寫作](https://hexo.io/zh-tw/docs/configuration.html#寫作)—連結錯誤
- [ ] 連結錯誤
⭕️ https://hexo.io/zh-tw/docs/asset-folders.html
❌ https://hexo.io/zh-tw/docs/docs/asset-folders.html
> post_asset_folder 啟動 [Asset 資料夾](https://hexo.io/zh-tw/docs/docs/permalinks.html)  false

**Comment by NoahDragon** [comment]
除了第二個是已知的問題外https://github.com/hexojs/hexo/issues/2563
其它可否請修改并提交PR呢？

**Comment by NoahDragon** [comment]
主題–發佈—顯示、資訊錯誤 Fixed https://github.com/hexojs/hexo/pull/2568

**Comment by NoahDragon** [comment]
Add Ref: https://github.com/hexojs/site/pull/483
