### ISSUE TITLE
Double TOC in chrome

### ISSUE THREAD

**Issue by RoamIn** [hexojs/site#540]
When open bookmark bar in [zh-cn/docs](https://hexo.io/zh-cn/docs/index.html), and scroll to bottom, it happens.

Chrome  60.0.3112.90，the latest Chrome too.

![bug](https://user-images.githubusercontent.com/11537595/29416255-13e75f82-8398-11e7-9d90-603c74a79626.png)

I found it ups to the screen resolution(2560*1440 2K)

**Comment by RoamIn** [comment]
the latest Chrome too

**Comment by NoahDragon** [comment]
I couldn't reproduce the issue. Can't afford a 2K monitor either. 😢

**Comment by JLHwung** [comment]
Can't reproduce either on Chrome 60 macOS 10.12. Could you disable the extension to see if this issue can be reproduced? Thank you.

**Comment by RoamIn** [comment]
If I disable the Adblock extension, it return to normalness. 
Seems to be extension problem.
Sorry.

**Comment by JLHwung** [comment]
Glad to hear you solve the issue.

**Comment by RoamIn** [comment]
![bug](https://user-images.githubusercontent.com/11537595/29457822-b7112088-844e-11e7-9a16-f526ed02a9fb.gif)
Probably browser render problem.
