### ISSUE TITLE
Is it possible to use hexo docs site theme?

### ISSUE THREAD

**Issue by Muyangmin** [hexojs/site#553]
I want to build a **project docs site** and I'm very fascinated with hexo docs site [https://hexo.io/docs/](https://hexo.io/docs/).  It is almost perfect for project docs:
* Left Navigation: show all article titles grouped by category
* Right Navigation: show all anchors (headers) in this article
* Clear and light render style

Unfortunately my website and front-end knowledge is so poor that I cannot find out a minimal set of code can be used to a new site to satisfy my needs as above.  

*I've tried to search by the "navy" name implied by the theme folder in this repo, but found nothing.* 

 Is there an easy way to use this theme into my project?  For example, just install by clone or copy few files and change some necessary configs.

**Comment by NoahDragon** [comment]
You could clone this repo https://github.com/hexojs/site.git , and modify the files under `source\docs` https://github.com/hexojs/site/tree/master/source/docs . Also, modify other places if necessary.
