### ISSUE TITLE
Mention hexo will transform every file in source/ unless excluded with skip_render.

### ISSUE THREAD

**Issue by JLHwung** [hexojs/site#581]
See https://github.com/hexojs/hexo/issues/1591. We need to highlight the `skip_render` usage on these case. The `skip_render` has 110+ related issues on hexo, it is important to state that considering on our user profile.

**Comment by stevenjoezhang** [comment]
It is necessary to remind developers that the `before_post_render` and `after_post_render` filters may be executed on non-markdown posts (e.g. `.js` or `.css` file), so it's important to check the file type passed in.

**Comment by stevenjoezhang** [comment]
Will be fixed in https://github.com/hexojs/hexo/pull/5118
