### ISSUE TITLE
themes are gone

### ISSUE THREAD

**Issue by ploctaux** [hexojs/site#626]
as first time user of hexo, i wanted to check out the themes section on the site.... i get a 404.

i did some digging and i saw on https://github.com/hexojs/hexojs.github.io that on jan 1, 2018 the **themes** folder is gone but the commit before that has it ! 

please bring it back, thanks and happy new year !

**Comment by varctrl** [comment]
i hopo so

**Comment by billzhonggz** [comment]
I found the same issue. Hope to be fixed as soon as possible.
