### ISSUE TITLE
Can we sort plugins/themes by date?

### ISSUE THREAD

**Issue by unnamed42** [hexojs/site#661]

**Comment by tcrowe** [comment]
Hi @unnamed42 if we wanted dates it would have to be added to the data files https://github.com/hexojs/site/blob/master/source/_data/themes.yml

It's unlikely that anyone will volunteer to go look up the dates added for all themes and plugins.

I would recommend we close this out unless someone is eager to do the hard work necessary.

**Comment by NoahDragon** [comment]
@tcrowe You are right. Let's close this for now.
