### ISSUE TITLE
Translate the documentation to portuguese. 

### ISSUE THREAD

**Issue by flowck** [hexojs/site#67]
Hey guys, I used Hexo to build my blog and recently I started to build my personal website with it and i'm really interested in translating the docs to portuguese which is my native language.

I want to know want do you think about this idea.

**Comment by Xuanwo** [comment]
That‘s wonderful!
If your are ready, you can create a pr, and we will commit it~

**Comment by flowck** [comment]
@Xuanwo I'm starting right now. I'll create a branch named "hx-pt" where I'll translate all the documentation.

**Comment by tommy351** [comment]
:+1:

**Comment by alexbruno** [comment]
Great! Can I collaborate too?

I'm from Brazil and would like to help to translating the docs to brazilian portuguese.

**Comment by Xuanwo** [comment]
@flowck Hello, I'm interested in your translation , please let me know what progress your are in and can I provide any help.
@alexbruno of course, this repo is open source, you have the right to do this, and I'm glad to see people in Brazil use hexo. It sounds wonderful !

**Comment by alexbruno** [comment]
Ok, I'm starting pt-br translation right now.

**Comment by ramonsantos** [comment]
@alexbruno, you need help in translation?

I'm brazilian too.

**Comment by lucianobarauna** [comment]
@ramonsantos  and @alexbruno 
I'm brazilian too.
Let's start translating the documentation of the Ixo until I was going to start more I visualized the issue of you and would like to know in which foot it is?

@Xuanwo 
How is the process for translation?

**Comment by NoahDragon** [comment]
@lucianobarauna Thanks for interesting in translation. The file structure would be like the following:

    https://github.com/hexojs/site/tree/master/source/ko

```
Fork this repo.
Add a new folder in Source named 'pt'
---- pt
  |----api
  |----docs
  |----index.jade
```

The api, docs, and index.jade could be copied from the source folder: https://github.com/hexojs/site/tree/master/source

**Comment by lucianobarauna** [comment]
Thanks!
I put pt-br because if it is only put pt implies that it is portuguese from portugal, do you have any problems regarding this?
There are linguistic variations between Portuguese from Portugal and Portuguese from Brazil.

**Comment by NoahDragon** [comment]
@lucianobarauna  Sorry I'm not familiar with the differences between Portuguese in Portugal and Brazil. pt-br is good for me.

I think you could commit in any language you prefer as when the PR merges the commit message could be modified.

**Comment by lucianobarauna** [comment]
All right, I'll keep the commits and pullrequest in English
Thanks for support

**Comment by ramonsantos** [comment]
Hello!

How to divide the work?
@lucianobarauna, you started the translation by which markdown file? Do you have a list of files with the translation completed?

**Comment by lucianobarauna** [comment]
Hi!
@ramonsantos 
Still no initial stage, I am still in the documentation index take a look at my last commit here: https://github.com/lucianobarauna/site/commits/new_translate_ptbr

PS: If you want we can exchange a better idea send me a message on twitter: @magoopv

**Comment by ramonsantos** [comment]
@lucianobarauna, I see that you are translating the part of 'docs', in this way, I will translate the part of 'api', okay?

**Comment by lucianobarauna** [comment]
ok @ramonsantos

**Comment by lucianobarauna** [comment]
@NoahDragon \o/
We finished the translation and put this question to be closed when the draw request to accept
The link to the submission request is this: https://github.com/hexojs/site/pull/605

**Comment by NoahDragon** [comment]
@lucianobarauna @ramonsantos Thank you. I can see the huge efforts you put into it. I really don't know the word to express my gratitude right now. Anyway, great job!
