### ISSUE TITLE
Disqus attribute left out of documentation

### ISSUE THREAD

**Issue by ncksllvn** [hexojs/site#78]
Unless I'm missing something, information on the attribute `disqus_shortname` is left out of the documentation. I really think this should be included there or at least with an empty value in `_config.yml`.

**Comment by tommy351** [comment]
Disqus is supported by the theme and is not a feature of Hexo itself.

**Comment by ncksllvn** [comment]
Ah I see. But then why cover the `comments` attribute in the Front-matter section?

**Comment by Xuanwo** [comment]
Hexo used to have `disque` bulit in, maybe we need remove it from hexo and just supply this in theme. So that we will not be confused by different place to set comments.
