### ISSUE TITLE
update docs with warning of incomplete wordpress migrator

### ISSUE THREAD

**Issue by jashsayani** [hexojs/site#811]
The wordpress migrator (1.0.0) is far from complete. I would personally call it 0.1.0 at this stage. There are some notable issues:
- [more tag not migrated](https://github.com/hexojs/hexo-migrator-wordpress/issues/33)
- [exporting images?](https://github.com/hexojs/hexo-migrator-wordpress/issues/34)
- [paragraphs lost post-migration](https://github.com/hexojs/hexo-migrator-wordpress/issues/35)
- [multiple categories exported as nested categories](https://github.com/hexojs/hexo-migrator-wordpress/issues/36)
- [image gallery inside post not migrated](https://github.com/hexojs/hexo-migrator-wordpress/issues/37)

I spent about 3 weeks building a hexo theme and now I noticed that the migrator is not complete and cannot handle many basic things. A warning on the [Migration page](https://hexo.io/docs/migration.html) should be added stating that there are many missing features in the migrator and only plain-text blogs can be migrated.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-migrator-wordpress/issues/54
