### ISSUE TITLE
Add checks during site build for themes and plugins

### ISSUE THREAD

**Issue by tomap** [hexojs/site#837]
In order to check the plugins and themes that are proposed, we could do the following.

For Themes, we could:
* Test if urls are still working (repo and demo)
* Clone the theme repo, and check if an extremely basic site can rend (simple hello world)
* Maybe a more complex version

For plugins, nearly the same:
* Check urls,
* Test installation
* Does a basic site still works after installation?

Two considerations:
1/ As this may take a huge amount of time, we could do that only on "theme/*" and "plugin/*" branches

2/ As those test might be incorrectly working for a number of reasons, we could, instead of hiding invalid plugins, add "validation" badges onto plugins "A", B", ... Depending on their results

The objective of all this is to propose better quality of plugins and themes to our users, to provide a better experience overall

I was starting to explore doing this for plugins. Tell me what you think.

Thank you

**Comment by YoshinoriN** [comment]
Totally agree with @tomap.
Maybe @tcrowe [has idea](https://github.com/hexojs/hexo/issues/3298#issuecomment-433181454) for 404 pages.

Btw, I tried to check 404 page using by [this chrome extensions](https://chrome.google.com/webstore/detail/check-my-links/ojkcdipcgfaekbeaelaapakgnjflfglf). 
But I was blocked to access to GitHub for few minutes reason of  mechanical access detected.

So, if we want to check 404 page using by automatically we have to control access span to GitHub.

**Comment by tomap** [comment]
Or we could start by plugins, npm install ... That would be long but would
tell us if it works
Not for themes thought

Le mer. 12 déc. 2018 à 16:10, YoshinoriN <notifications@github.com> a
écrit :

**Comment by YoshinoriN** [comment]
> Or we could start by plugins, npm install
It's good idea 😄

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/site/pull/1458#issuecomment-650570884

**Comment by RammusXu** [comment]
Or hexo can create an official action, every theme/plugin who want to add to official list should install this action and pass in their own repo.

This action can be more complicated and make sure themes/plugins are more reliable.

**Comment by jiangtj** [comment]
> Or hexo can create an official [Github Action](https://github.com/features/actions) and [template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository), every theme/plugin who want to add to official list should install this action and pass in their own repo.

This idea gave me inspiration. Hexo runs on the node platform, so we can create a test lib for hexo, e.g. `hexo-test`. And through it simplifies some test code.

Currently, if we need to test the filter generator, etc., we need to create a separate js file.

```js
// main.js
hexo.extend.filter.register(type, require('filter'));
// filter.js
module.exports = () => ....
```

And we only test the separate js file.

```js
const filterFn = require('filter');
const result = filterFn(args);
// ...
```

Maybe we can achieve the following operations through `hexo-test`.

```js
// main.js
hexo.extend.filter.register(type, () => ...);

// test.js
const hexo = new HexoTestInstance();
hexo.loadScript('main.js');
const data = hexo.generateMockData(type);//generate or custom data
hexo.execFilter(type, data).then(result => ...);
```

**Comment by tomap** [comment]
Seems Fixed!
