### ISSUE TITLE
Update docs to explain include ranged code lines

### ISSUE THREAD

**Issue by YoshinoriN** [hexojs/site#858]
New feature. We will going to write doc after next release.

https://github.com/hexojs/hexo/pull/3393

**Comment by curbengh** [comment]
Ping @kezhenxu94

**Comment by kezhenxu94** [comment]
> Ping @kezhenxu94

Hi @curbengh @YoshinoriN , am I supposed to undertake this task of updating the docs, please let me know if I can help on this :)

**Comment by curbengh** [comment]
Yes, please.
