### ISSUE TITLE
Possible to make more than just Title with command line?

### ISSUE THREAD

**Issue by Zodzie** [hexojs/site#87]
I would like to do $ hexo new "title" content-within-blogpost

**Comment by bojidar-bg** [comment]
Shouldn't this go to https://github.com/hexojs/hexo/issues ?

**Comment by leesei** [comment]
1. Should be in https://github.com/hexojs/hexo/issues
2. Is opening the file such a tedious task?

**Comment by Zodzie** [comment]
The point would be to fufill a one-liner blog complete with title and content inside. Good for making quick blog post from mobile device via text message

**Comment by leesei** [comment]
This can be easily done with external scripting, no need to add to hexo core.

```sh
TITLE=$1
shift
CONTENT=$@
MDFILE=$(hexo new $1 | cut -d" " -f4)
echo "$CONTENT" >> $MDFILE
```

**Comment by Zodzie** [comment]
I can send a server command to my website via my mobile device already. But I don't want to send a shell script. I thinkg it would increase the value of this software 10 fold.

**Comment by leesei** [comment]
What I suggest is that you send the `title` and `content` from mobile to server, not the script.
You can do some scripting on server side to archive the same functionality without needing to add feature to `hexo-cli`.

**Comment by Zodzie** [comment]
thx a lot for advice
