### ISSUE TITLE
Is there a way to make `{% asset_img image.jpg This is an image %}` not executed

### ISSUE THREAD

**Issue by BovenPeng** [hexojs/site#942]
I want to show `{% asset_img image.jpg This is an image %}` as a code sample in the blog configured of **Hexo**.
But it will be parsed and executed as a code to add *img.jpg* to the blog even if there is no such picture in the corresponding folder.
And I have tried all the ways in **markdown grammar** to mark code such as:
- as *inline* code with single backticks, e.g. ``{% asset_img image.jpg This is an image %}``, or

- as a code *block* using indentation:

  ```
      {% asset_img image.jpg This is an image %}
  ```

  or fences made of three or more backticks or tildes:

  ```
  
  ```

  {% asset_img image.jpg This is an image %}

  ```
  ~~~
  {% asset_img image.jpg This is an image %}
  ~~~
  ```

- ```
  {% asset_img image.jpg This is an image %}
  ```
  
  ~~~
  
  {% asset_img image.jpg This is an image %}
  
  ~~~
But all of them are not work.
And I can't delete the corresponding folder because there are other resources.

So I am wondering if there is a way to make `{% asset_img image.jpg This is an image %}` not parsed and executed in the markdown file?
Thanks sincerely.

**Comment by curbengh** [comment]
Triple backticks should work, which is what [this site use](https://github.com/hexojs/site/raw/master/source/docs/tag-plugins.md) to escape `asset_img`.

Try [`{% raw %}`](https://hexo.io/docs/tag-plugins#Raw),
```
{% raw %}
{% asset_img %}
{% endraw %}
```

**Comment by BovenPeng** [comment]
Sorry to respond to you so late.
`{% raw %}` does work!
Thanks again.
