### ISSUE TITLE
Update docs to include current way to show img with alt text

### ISSUE THREAD

**Issue by GiantZOC** [hexojs/site#960]
I thought that the img tag was broken.  The documented method has brackets for the title and alt text.  It currently appears to work only if you use double and single quotes.

Docs:
{% img [class names] /path/to/image [width] [height] [title text [alt text]] %}
Working:
{% img [class names] /path/to/image [width] [height] "title text 'alt text'" %}

https://stackoverflow.com/questions/47665964/hexo-alt-text-doesnt-work
https://github.com/hexojs/hexo/issues/2887

**Comment by NoahDragon** [comment]
Thanks for collaboration. This will save many people a day. :)
